Rammbock release notes
======================

0.4.0
-----

* Background handlers for asynchronous message handling
* Bags of optional elements in optional order
* IPv6 support
* Struct alignment
* Numerous fixes and enhancements

0.3.0
-----

* Signed integers
* Support dynamic length headers
* SCTP protocol
* Free length lists (*)
* Many minor fixes and improvements

0.2.1
-----

* Fix links in readme
* Add full path to validation errors and missing fields
* Minor fixes and cleanup

0.2.0
-----

* Rewrote entire library to use protocol and message templates

0.1.0
-----

* First public release
